
meta_product_name: "Bhavana Experiences"
meta_title: "Bhavana Experiences - Cultivate the mind"
meta_description: "We organise budget tours to India. Experience the 'Real India' accompanied by one British and
one Indian tour guide. We're here to encourage you to step out of your comfort zone without compromising your comfort."
meta_image: "taj.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
